<a href="https://colab.research.google.com/github/nedokormysh/Stepik_Ai_edu_DL_intro/blob/week_6_enhance_speed/NN_improvements_hometask.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашнее задание

В этом домашнем задании вы обучите полносвязную нейронную сеть для решения задачи классификации на датасете CIFAR-10.

Это домашнее задание оформлено в не совсем традиционном формате. Не хочется заставлять вас копировать код. Вы будете менять уже существующую архитектуру, а затем отвечать на вопросы.

## Задание 1

Запустите данный изначально код и замерьте качество (accuracy) на тестовых данных. Ответ округлите до целого числа.



In [21]:
import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms
import random
import numpy as np

np.random.seed(0)
random.seed(0)
torch.manual_seed(0)

In [22]:
# Check Device configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Define Hyper-parameters
input_size = 3072
num_classes = 10
num_epochs = 10
batch_size = 32
learning_rate = 0.001

In [23]:
# MNIST dataset
transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

train_dataset = torchvision.datasets.CIFAR10(root='../../data',
                                           train=True,
                                           transform=transform,
                                           download=True)

test_dataset = torchvision.datasets.CIFAR10(root='../../data',
                                          train=False,
                                          transform=transform)

Files already downloaded and verified


In [24]:
# Data loader
train_loader = torch.utils.data.DataLoader(dataset=train_dataset,
                                           batch_size=batch_size,
                                           shuffle=True)

test_loader = torch.utils.data.DataLoader(dataset=test_dataset,
                                          batch_size=batch_size,
                                          shuffle=False)

In [25]:
# # Fully connected neural network
# class NeuralNet(nn.Module):
#     def __init__(self, input_size, num_classes):
#         super(NeuralNet, self).__init__()
#         self.fc1 = nn.Linear(input_size, 1000)
#         self.relu = nn.ReLU()
#         self.fc2 = nn.Linear(1000, num_classes)
# #        self.apply(self._init_weights)

#     def _init_weights(self, module): # метод для различных "умных" инициализаций весов
#         if isinstance(module, nn.Linear):
#             module.weight.data.normal_(mean=0.0, std=0.15)
#             if module.bias is not None:
#                 module.bias.data.zero_()

#     def forward(self, x):
#         out = self.fc1(x)
#         out = self.relu(out)
#         out = self.fc2(out)
#         return out

# model = NeuralNet(input_size, num_classes).to(device)

In [26]:
# model

In [27]:
# # Loss and optimizer
# criterion = nn.CrossEntropyLoss()
# optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [28]:
# np.random.seed(0)
# random.seed(0)
# torch.manual_seed(0)

# loss_log = []

# # Train the model
# total_step = len(train_loader)
# for epoch in range(num_epochs):
#     for i, (images, labels) in enumerate(train_loader):
#         # Move tensors to the configured device
#         images = images.reshape(-1, 32*32*3).to(device)
#         labels = labels.to(device)

#         # Forward pass
#         outputs = model(images)
#         loss = criterion(outputs, labels)

#         # Backprpagation and optimization
#         optimizer.zero_grad()
#         loss.backward()
#         optimizer.step()

#         if (i+1) % 100 == 0:
#             print ('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}'
#                    .format(epoch+1, num_epochs, i+1, total_step, loss.item()))
#             loss_log.append(loss.data.cpu().numpy())

In [29]:
# from matplotlib import pyplot as plt

# plt.figure(figsize=(10,8))
# plt.plot(loss_log)

In [30]:
# np.random.seed(0)
# random.seed(0)
# torch.manual_seed(0)

# # Test the model
# # In the test phase, don't need to compute gradients (for memory efficiency)
# with torch.no_grad():
#     correct = 0
#     total = 0
#     for images, labels in test_loader:
#         images = images.reshape(-1, 32*32*3).to(device)
#         labels = labels.to(device)
#         outputs = model(images)
#         _, predicted = torch.max(outputs.data, 1)
#         total += labels.size(0)
#         correct += (predicted == labels).sum().item()

#     print('Accuracy of the network on the test images: {} %'.format(100 * correct / total))

# # Save the model checkpoint
# torch.save(model.state_dict(), 'model.ckpt')

## Задание 2

Добавьте еще один полносвязный слой (перед выходным) из 100 нейронов + функцию активации ReLU и запустите обучение. Выберите в ответе accuracy, наиболее близкую к полученной на тесте.



In [31]:
# Fully connected neural network
class NeuralNet_2(nn.Module):
    def __init__(self, input_size, num_classes):
        super(NeuralNet_2, self).__init__()
        self.fc1 = nn.Linear(input_size, 1000)
        self.relu = nn.ReLU()
        self.fc1_1 = nn.Linear(1000, 100)
        self.relu1_1 = nn.ReLU()
        self.fc2 = nn.Linear(100, num_classes)
#        self.apply(self._init_weights)

    def _init_weights(self, module): # метод для различных "умных" инициализаций весов
        if isinstance(module, nn.Linear):
            module.weight.data.normal_(mean=0.0, std=0.15)
            if module.bias is not None:
                module.bias.data.zero_()

    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc1_1(out)
        out = self.relu1_1(out)
        out = self.fc2(out)
        return out

model_2 = NeuralNet_2(input_size, num_classes).to(device)

In [32]:
model_2

NeuralNet_2(
  (fc1): Linear(in_features=3072, out_features=1000, bias=True)
  (relu): ReLU()
  (fc1_1): Linear(in_features=1000, out_features=100, bias=True)
  (relu1_1): ReLU()
  (fc2): Linear(in_features=100, out_features=10, bias=True)
)

In [35]:
# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model_2.parameters(), lr=learning_rate)

In [36]:
np.random.seed(0)
random.seed(0)
torch.manual_seed(0)

loss_log = []

# Train the model
total_step = len(train_loader)
for epoch in range(num_epochs):
    for i, (images, labels) in enumerate(train_loader):
        # Move tensors to the configured device
        images = images.reshape(-1, 32*32*3).to(device)
        labels = labels.to(device)

        # Forward pass
        outputs = model_2(images)
        loss = criterion(outputs, labels)

        # Backprpagation and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if (i+1) % 100 == 0:
            print ('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}'
                   .format(epoch+1, num_epochs, i+1, total_step, loss.item()))
            loss_log.append(loss.data.cpu().numpy())

Epoch [1/10], Step [100/1563], Loss: 2.1337
Epoch [1/10], Step [200/1563], Loss: 1.8732
Epoch [1/10], Step [300/1563], Loss: 1.6119
Epoch [1/10], Step [400/1563], Loss: 1.8913
Epoch [1/10], Step [500/1563], Loss: 1.8232
Epoch [1/10], Step [600/1563], Loss: 1.7193
Epoch [1/10], Step [700/1563], Loss: 1.4366
Epoch [1/10], Step [800/1563], Loss: 1.6793
Epoch [1/10], Step [900/1563], Loss: 1.5317
Epoch [1/10], Step [1000/1563], Loss: 1.4085
Epoch [1/10], Step [1100/1563], Loss: 1.6790
Epoch [1/10], Step [1200/1563], Loss: 1.5380
Epoch [1/10], Step [1300/1563], Loss: 1.4259
Epoch [1/10], Step [1400/1563], Loss: 1.4185
Epoch [1/10], Step [1500/1563], Loss: 1.4559
Epoch [2/10], Step [100/1563], Loss: 1.5025
Epoch [2/10], Step [200/1563], Loss: 1.4655
Epoch [2/10], Step [300/1563], Loss: 1.4740
Epoch [2/10], Step [400/1563], Loss: 1.5843
Epoch [2/10], Step [500/1563], Loss: 1.6245
Epoch [2/10], Step [600/1563], Loss: 1.5893
Epoch [2/10], Step [700/1563], Loss: 1.5943
Epoch [2/10], Step [800/15

In [37]:
np.random.seed(0)
random.seed(0)
torch.manual_seed(0)

# Test the model
# In the test phase, don't need to compute gradients (for memory efficiency)
with torch.no_grad():
    correct = 0
    total = 0
    for images, labels in test_loader:
        images = images.reshape(-1, 32*32*3).to(device)
        labels = labels.to(device)
        outputs = model_2(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    print('Accuracy of the network on the test images: {} %'.format(100 * correct / total))

# Save the model checkpoint
torch.save(model_2.state_dict(), 'model_2_extra_layer.ckpt')

Accuracy of the network on the test images: 51.53 %


## Задание 3

Теперь обучите полносвязную сеть с несколькими линейными слоями с числом нейронов: 1024, 512, 256, 128, 64 соответственно + функцией ReLU на выходе из каждого внутреннего слоя. В ответе - accuracy, округленная до целого числа.



In [38]:
# Fully connected neural network
class NeuralNet_3(nn.Module):
    def __init__(self, input_size, num_classes):
        super(NeuralNet_3, self).__init__()
        self.fc1 = nn.Linear(input_size, 1024)
        self.relu1 = nn.ReLU()
        self.fc2 = nn.Linear(1024, 512)
        self.relu2 = nn.ReLU()
        self.fc3 = nn.Linear(512, 256)
        self.relu3 = nn.ReLU()
        self.fc4 = nn.Linear(256, 128)
        self.relu4 = nn.ReLU()
        self.fc5 = nn.Linear(128, 64)
        self.relu5 = nn.ReLU()
        self.fc_last = nn.Linear(64, num_classes)
#        self.apply(self._init_weights)

    def _init_weights(self, module): # метод для различных "умных" инициализаций весов
        if isinstance(module, nn.Linear):
            module.weight.data.normal_(mean=0.0, std=0.15)
            if module.bias is not None:
                module.bias.data.zero_()

    def forward(self, x):
        out = self.fc1(x)
        out = self.relu1(out)
        out = self.fc2(out)
        out = self.relu2(out)
        out = self.fc3(out)
        out = self.relu3(out)
        out = self.fc4(out)
        out = self.relu4(out)
        out = self.fc5(out)
        out = self.relu5(out)
        out = self.fc_last(out)
        return out

model_3 = NeuralNet_3(input_size, num_classes).to(device)

In [39]:
model_3

NeuralNet_3(
  (fc1): Linear(in_features=3072, out_features=1024, bias=True)
  (relu1): ReLU()
  (fc2): Linear(in_features=1024, out_features=512, bias=True)
  (relu2): ReLU()
  (fc3): Linear(in_features=512, out_features=256, bias=True)
  (relu3): ReLU()
  (fc4): Linear(in_features=256, out_features=128, bias=True)
  (relu4): ReLU()
  (fc5): Linear(in_features=128, out_features=64, bias=True)
  (relu5): ReLU()
  (fc_last): Linear(in_features=64, out_features=10, bias=True)
)

In [40]:
# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model_3.parameters(), lr=learning_rate)

In [41]:
np.random.seed(0)
random.seed(0)
torch.manual_seed(0)

loss_log = []

# Train the model
total_step = len(train_loader)
for epoch in range(num_epochs):
    for i, (images, labels) in enumerate(train_loader):
        # Move tensors to the configured device
        images = images.reshape(-1, 32*32*3).to(device)
        labels = labels.to(device)

        # Forward pass
        outputs = model_3(images)
        loss = criterion(outputs, labels)

        # Backprpagation and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if (i+1) % 100 == 0:
            print ('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}'
                   .format(epoch+1, num_epochs, i+1, total_step, loss.item()))
            loss_log.append(loss.data.cpu().numpy())

Epoch [1/10], Step [100/1563], Loss: 2.3296
Epoch [1/10], Step [200/1563], Loss: 1.9713
Epoch [1/10], Step [300/1563], Loss: 1.7932
Epoch [1/10], Step [400/1563], Loss: 1.6880
Epoch [1/10], Step [500/1563], Loss: 1.7460
Epoch [1/10], Step [600/1563], Loss: 1.7006
Epoch [1/10], Step [700/1563], Loss: 1.4427
Epoch [1/10], Step [800/1563], Loss: 1.7598
Epoch [1/10], Step [900/1563], Loss: 1.5572
Epoch [1/10], Step [1000/1563], Loss: 1.5407
Epoch [1/10], Step [1100/1563], Loss: 1.8749
Epoch [1/10], Step [1200/1563], Loss: 1.7445
Epoch [1/10], Step [1300/1563], Loss: 1.6308
Epoch [1/10], Step [1400/1563], Loss: 1.4811
Epoch [1/10], Step [1500/1563], Loss: 1.3879
Epoch [2/10], Step [100/1563], Loss: 1.5072
Epoch [2/10], Step [200/1563], Loss: 1.4394
Epoch [2/10], Step [300/1563], Loss: 1.3425
Epoch [2/10], Step [400/1563], Loss: 1.9214
Epoch [2/10], Step [500/1563], Loss: 1.4546
Epoch [2/10], Step [600/1563], Loss: 1.5362
Epoch [2/10], Step [700/1563], Loss: 1.4518
Epoch [2/10], Step [800/15

In [42]:
np.random.seed(0)
random.seed(0)
torch.manual_seed(0)

# Test the model
# In the test phase, don't need to compute gradients (for memory efficiency)
with torch.no_grad():
    correct = 0
    total = 0
    for images, labels in test_loader:
        images = images.reshape(-1, 32*32*3).to(device)
        labels = labels.to(device)
        outputs = model_3(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    print('Accuracy of the network on the test images: {} %'.format(100 * correct / total))

# Save the model checkpoint
torch.save(model_3.state_dict(), 'model_3_diff_layers.ckpt')

Accuracy of the network on the test images: 53.35 %


## Задание 4

К архитектуре из предыдущего задания добавьте Dropout(0.2) перед слоями из 1024 и 256 нейронов. Увеличилась ли accuracy по сравнению с предыдущим заданием?



In [44]:
# Fully connected neural network
class NeuralNet_4(nn.Module):
    def __init__(self, input_size, num_classes):
        super(NeuralNet_4, self).__init__()
        self.fc1 = nn.Linear(input_size, 1024)
        self.relu1 = nn.ReLU()
        self.dp1 = nn.Dropout(0.2)
        self.fc2 = nn.Linear(1024, 512)
        self.relu2 = nn.ReLU()
        self.fc3 = nn.Linear(512, 256)
        self.relu3 = nn.ReLU()
        self.dp2 = nn.Dropout(0.2)
        self.fc4 = nn.Linear(256, 128)
        self.relu4 = nn.ReLU()
        self.fc5 = nn.Linear(128, 64)
        self.relu5 = nn.ReLU()
        self.fc_last = nn.Linear(64, num_classes)
#        self.apply(self._init_weights)

    def _init_weights(self, module): # метод для различных "умных" инициализаций весов
        if isinstance(module, nn.Linear):
            module.weight.data.normal_(mean=0.0, std=0.15)
            if module.bias is not None:
                module.bias.data.zero_()

    def forward(self, x):
        out = self.fc1(x)
        out = self.relu1(out)
        out = self.dp1(out)
        out = self.fc2(out)
        out = self.relu2(out)
        out = self.fc3(out)
        out = self.relu3(out)
        out = self.dp2(out)
        out = self.fc4(out)
        out = self.relu4(out)
        out = self.fc5(out)
        out = self.relu5(out)
        out = self.fc_last(out)
        return out

model_4 = NeuralNet_4(input_size, num_classes).to(device)

In [45]:
model_4

NeuralNet_4(
  (fc1): Linear(in_features=3072, out_features=1024, bias=True)
  (relu1): ReLU()
  (dp1): Dropout(p=0.2, inplace=False)
  (fc2): Linear(in_features=1024, out_features=512, bias=True)
  (relu2): ReLU()
  (fc3): Linear(in_features=512, out_features=256, bias=True)
  (relu3): ReLU()
  (dp2): Dropout(p=0.2, inplace=False)
  (fc4): Linear(in_features=256, out_features=128, bias=True)
  (relu4): ReLU()
  (fc5): Linear(in_features=128, out_features=64, bias=True)
  (relu5): ReLU()
  (fc_last): Linear(in_features=64, out_features=10, bias=True)
)

In [46]:
# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model_4.parameters(), lr=learning_rate)

In [47]:
np.random.seed(0)
random.seed(0)
torch.manual_seed(0)

loss_log = []

# Train the model
total_step = len(train_loader)
for epoch in range(num_epochs):
    for i, (images, labels) in enumerate(train_loader):
        # Move tensors to the configured device
        images = images.reshape(-1, 32*32*3).to(device)
        labels = labels.to(device)

        # Forward pass
        outputs = model_4(images)
        loss = criterion(outputs, labels)

        # Backprpagation and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if (i+1) % 100 == 0:
            print ('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}'
                   .format(epoch+1, num_epochs, i+1, total_step, loss.item()))
            loss_log.append(loss.data.cpu().numpy())

Epoch [1/10], Step [100/1563], Loss: 2.1819
Epoch [1/10], Step [200/1563], Loss: 2.2000
Epoch [1/10], Step [300/1563], Loss: 1.7951
Epoch [1/10], Step [400/1563], Loss: 1.7220
Epoch [1/10], Step [500/1563], Loss: 1.8447
Epoch [1/10], Step [600/1563], Loss: 1.8877
Epoch [1/10], Step [700/1563], Loss: 1.4983
Epoch [1/10], Step [800/1563], Loss: 1.7759
Epoch [1/10], Step [900/1563], Loss: 1.5206
Epoch [1/10], Step [1000/1563], Loss: 1.5457
Epoch [1/10], Step [1100/1563], Loss: 1.8365
Epoch [1/10], Step [1200/1563], Loss: 1.8503
Epoch [1/10], Step [1300/1563], Loss: 1.7546
Epoch [1/10], Step [1400/1563], Loss: 1.6282
Epoch [1/10], Step [1500/1563], Loss: 1.5057
Epoch [2/10], Step [100/1563], Loss: 1.5387
Epoch [2/10], Step [200/1563], Loss: 1.3722
Epoch [2/10], Step [300/1563], Loss: 1.3421
Epoch [2/10], Step [400/1563], Loss: 1.8931
Epoch [2/10], Step [500/1563], Loss: 1.6172
Epoch [2/10], Step [600/1563], Loss: 1.6632
Epoch [2/10], Step [700/1563], Loss: 1.4547
Epoch [2/10], Step [800/15

In [48]:
np.random.seed(0)
random.seed(0)
torch.manual_seed(0)

# Test the model
# In the test phase, don't need to compute gradients (for memory efficiency)
with torch.no_grad():
    correct = 0
    total = 0
    for images, labels in test_loader:
        images = images.reshape(-1, 32*32*3).to(device)
        labels = labels.to(device)
        outputs = model_4(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    print('Accuracy of the network on the test images: {} %'.format(100 * correct / total))

# Save the model checkpoint
torch.save(model_4.state_dict(), 'model_4_drop.ckpt')

Accuracy of the network on the test images: 51.47 %


## Задание 5

Уберите Dropout, но добавьте BatchNorm перед входом в те же линейные слои. Увеличилась ли accuracy по сравнению с заданием 3?



In [71]:
# Fully connected neural network
class NeuralNet_5(nn.Module):
    def __init__(self, input_size, num_classes):
        super(NeuralNet_5, self).__init__()
        self.fc1 = nn.Linear(input_size, 1024)
        self.relu1 = nn.ReLU()
        self.bn1 = nn.BatchNorm1d(1024)
        self.fc2 = nn.Linear(1024, 512)
        self.relu2 = nn.ReLU()
        self.fc3 = nn.Linear(512, 256)
        self.relu3 = nn.ReLU()
        self.bn2 = nn.BatchNorm1d(256)
        self.fc4 = nn.Linear(256, 128)
        self.relu4 = nn.ReLU()
        self.fc5 = nn.Linear(128, 64)
        self.relu5 = nn.ReLU()
        self.fc_last = nn.Linear(64, num_classes)
#        self.apply(self._init_weights)

    def _init_weights(self, module): # метод для различных "умных" инициализаций весов
        if isinstance(module, nn.Linear):
            module.weight.data.normal_(mean=0.0, std=0.15)
            if module.bias is not None:
                module.bias.data.zero_()

    def forward(self, x):
        out = self.fc1(x)
        out = self.relu1(out)
        out = self.bn1(out)
        out = self.fc2(out)
        out = self.relu2(out)
        out = self.fc3(out)
        out = self.relu3(out)
        out = self.bn2(out)
        out = self.fc4(out)
        out = self.relu4(out)
        out = self.fc5(out)
        out = self.relu5(out)
        out = self.fc_last(out)
        return out

model_5 = NeuralNet_5(input_size, num_classes).to(device)

In [72]:
model_5

NeuralNet_5(
  (fc1): Linear(in_features=3072, out_features=1024, bias=True)
  (relu1): ReLU()
  (bn1): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (fc2): Linear(in_features=1024, out_features=512, bias=True)
  (relu2): ReLU()
  (fc3): Linear(in_features=512, out_features=256, bias=True)
  (relu3): ReLU()
  (bn2): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (fc4): Linear(in_features=256, out_features=128, bias=True)
  (relu4): ReLU()
  (fc5): Linear(in_features=128, out_features=64, bias=True)
  (relu5): ReLU()
  (fc_last): Linear(in_features=64, out_features=10, bias=True)
)

In [73]:
# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model_5.parameters(), lr=learning_rate)

In [74]:
np.random.seed(0)
random.seed(0)
torch.manual_seed(0)

loss_log = []

# Train the model
total_step = len(train_loader)
for epoch in range(num_epochs):
    for i, (images, labels) in enumerate(train_loader):
        # Move tensors to the configured device
        images = images.reshape(-1, 32*32*3).to(device)
        labels = labels.to(device)

        # Forward pass
        outputs = model_5(images)
        loss = criterion(outputs, labels)

        # Backprpagation and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if (i+1) % 100 == 0:
            print ('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}'
                   .format(epoch+1, num_epochs, i+1, total_step, loss.item()))
            loss_log.append(loss.data.cpu().numpy())

Epoch [1/10], Step [100/1563], Loss: 2.3554
Epoch [1/10], Step [200/1563], Loss: 1.9402
Epoch [1/10], Step [300/1563], Loss: 1.7799
Epoch [1/10], Step [400/1563], Loss: 1.8867
Epoch [1/10], Step [500/1563], Loss: 1.8736
Epoch [1/10], Step [600/1563], Loss: 1.8231
Epoch [1/10], Step [700/1563], Loss: 1.5780
Epoch [1/10], Step [800/1563], Loss: 1.8574
Epoch [1/10], Step [900/1563], Loss: 1.5460
Epoch [1/10], Step [1000/1563], Loss: 1.5374
Epoch [1/10], Step [1100/1563], Loss: 1.8431
Epoch [1/10], Step [1200/1563], Loss: 1.7315
Epoch [1/10], Step [1300/1563], Loss: 1.6013
Epoch [1/10], Step [1400/1563], Loss: 1.5659
Epoch [1/10], Step [1500/1563], Loss: 1.4564
Epoch [2/10], Step [100/1563], Loss: 1.5531
Epoch [2/10], Step [200/1563], Loss: 1.4152
Epoch [2/10], Step [300/1563], Loss: 1.6362
Epoch [2/10], Step [400/1563], Loss: 1.6650
Epoch [2/10], Step [500/1563], Loss: 1.4063
Epoch [2/10], Step [600/1563], Loss: 1.6981
Epoch [2/10], Step [700/1563], Loss: 1.4597
Epoch [2/10], Step [800/15

In [56]:
np.random.seed(0)
random.seed(0)
torch.manual_seed(0)

# Test the model
# In the test phase, don't need to compute gradients (for memory efficiency)
with torch.no_grad():
    correct = 0
    total = 0
    for images, labels in test_loader:
        images = images.reshape(-1, 32*32*3).to(device)
        labels = labels.to(device)
        outputs = model_5(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    print('Accuracy of the network on the test images: {} %'.format(100 * correct / total))

# Save the model checkpoint
torch.save(model_5.state_dict(), 'model_5_batchnorm.ckpt')

Accuracy of the network on the test images: 51.99 %


## Задание 6

Теперь пробуйте что угодно:
* разное число линейных слоев
* разные функции активации (вместо ReLU)
* комбинации Dropout / BatchNorm
* можете попробовать умные инициализации весов и другие трюки из урока

Цель - добиться наибольшей accuracy на тесте.

In [80]:
# Fully connected neural network
class NeuralNet_6(nn.Module):
    def __init__(self, input_size, num_classes):
        super(NeuralNet_6, self).__init__()
        self.fc1 = nn.Linear(input_size, 1024)
        self.relu1 = nn.ReLU()
        self.bn1 = nn.BatchNorm1d(1024)
        self.fc2 = nn.Linear(1024, 512)
        self.relu2 = nn.ReLU()
        self.fc3 = nn.Linear(512, 256)
        self.relu3 = nn.ReLU()
        self.bn2 = nn.BatchNorm1d(256)
        self.fc4 = nn.Linear(256, 128)
        self.relu4 = nn.ReLU()
        self.fc5 = nn.Linear(128, 64)
        self.relu5 = nn.ReLU()
        self.fc_last = nn.Linear(64, num_classes)
        # self.apply(self._init_weights)

        nn.init.xavier_uniform_(self.fc1.weight)
        nn.init.xavier_uniform_(self.fc2.weight)

    def _init_weights(self, module): # метод для различных "умных" инициализаций весов
        if isinstance(module, nn.Linear):
            module.weight.data.normal_(mean=0.0, std=0.15)
            if module.bias is not None:
                module.bias.data.zero_()

    def forward(self, x):
        out = self.fc1(x)
        out = self.relu1(out)
        out = self.bn1(out)
        # out = self.apply(out)
        out = self.fc2(out)
        out = self.relu2(out)
        out = self.fc3(out)
        out = self.relu3(out)
        out = self.bn2(out)
        out = self.fc4(out)
        out = self.relu4(out)
        out = self.fc5(out)
        out = self.relu5(out)
        out = self.fc_last(out)
        return out

model_6 = NeuralNet_6(input_size, num_classes).to(device)

In [81]:
model_6

NeuralNet_6(
  (fc1): Linear(in_features=3072, out_features=1024, bias=True)
  (relu1): ReLU()
  (bn1): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (fc2): Linear(in_features=1024, out_features=512, bias=True)
  (relu2): ReLU()
  (fc3): Linear(in_features=512, out_features=256, bias=True)
  (relu3): ReLU()
  (bn2): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (fc4): Linear(in_features=256, out_features=128, bias=True)
  (relu4): ReLU()
  (fc5): Linear(in_features=128, out_features=64, bias=True)
  (relu5): ReLU()
  (fc_last): Linear(in_features=64, out_features=10, bias=True)
)

In [82]:
# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model_6.parameters(), lr=learning_rate)

In [83]:
np.random.seed(0)
random.seed(0)
torch.manual_seed(0)

loss_log = []

# Train the model
total_step = len(train_loader)
for epoch in range(num_epochs):
    for i, (images, labels) in enumerate(train_loader):
        # Move tensors to the configured device
        images = images.reshape(-1, 32*32*3).to(device)
        labels = labels.to(device)

        # Forward pass
        outputs = model_6(images)
        loss = criterion(outputs, labels)

        # Backprpagation and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if (i+1) % 100 == 0:
            print ('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}'
                   .format(epoch+1, num_epochs, i+1, total_step, loss.item()))
            loss_log.append(loss.data.cpu().numpy())

Epoch [1/10], Step [100/1563], Loss: 2.2526
Epoch [1/10], Step [200/1563], Loss: 2.0689
Epoch [1/10], Step [300/1563], Loss: 1.7677
Epoch [1/10], Step [400/1563], Loss: 1.7969
Epoch [1/10], Step [500/1563], Loss: 1.9321
Epoch [1/10], Step [600/1563], Loss: 1.8568
Epoch [1/10], Step [700/1563], Loss: 1.5717
Epoch [1/10], Step [800/1563], Loss: 1.8656
Epoch [1/10], Step [900/1563], Loss: 1.5930
Epoch [1/10], Step [1000/1563], Loss: 1.5377
Epoch [1/10], Step [1100/1563], Loss: 1.7801
Epoch [1/10], Step [1200/1563], Loss: 1.7620
Epoch [1/10], Step [1300/1563], Loss: 1.5807
Epoch [1/10], Step [1400/1563], Loss: 1.6189
Epoch [1/10], Step [1500/1563], Loss: 1.4602
Epoch [2/10], Step [100/1563], Loss: 1.5028
Epoch [2/10], Step [200/1563], Loss: 1.3272
Epoch [2/10], Step [300/1563], Loss: 1.5864
Epoch [2/10], Step [400/1563], Loss: 1.6253
Epoch [2/10], Step [500/1563], Loss: 1.3959
Epoch [2/10], Step [600/1563], Loss: 1.6861
Epoch [2/10], Step [700/1563], Loss: 1.4488
Epoch [2/10], Step [800/15

In [84]:
np.random.seed(0)
random.seed(0)
torch.manual_seed(0)

# Test the model
# In the test phase, don't need to compute gradients (for memory efficiency)
with torch.no_grad():
    correct = 0
    total = 0
    for images, labels in test_loader:
        images = images.reshape(-1, 32*32*3).to(device)
        labels = labels.to(device)
        outputs = model_6(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    print('Accuracy of the network on the test images: {} %'.format(100 * correct / total))

# Save the model checkpoint
torch.save(model_6.state_dict(), 'model_6_xavier.ckpt')

Accuracy of the network on the test images: 53.64 %
